#!/bin/bash

echo "🔧 GitHub Sync 插件详细配置指南"
echo "================================="
echo ""

echo "📋 第1步：基础配置"
echo ""
echo "在 Obsidian → 设置 → GitHub Sync 中填写："
echo ""
echo "Repository Settings:"
echo "  Repository Name: freedomshannon/blog"
echo "  Branch: main"
echo "  GitHub Token: [您的_GitHub_Token]"
echo ""

echo "📂 第2步：路径映射配置"
echo ""
echo "Sync Settings："
echo "  Local Path -> Remote Path"
echo ""
echo "  博客文章/ -> posts/"
echo "  博客图片/images/ -> public/images/"
echo "  博客图片/covers/ -> public/covers/"
echo ""

echo "⚙️ 第3步：同步选项"
echo ""
echo "建议配置："
echo "  ✅ Auto-sync on file change: false (手动控制)"
echo "  ✅ Sync on startup: false"
echo "  ✅ Ignore .obsidian folder: true"
echo "  ✅ Create commit message: true"
echo ""

echo "🔍 第4步：忽略文件配置"
echo ""
echo "在 .gitignore 中添加（插件会自动处理）："
echo "  .obsidian/"
echo "  .trash/"
echo "  .DS_Store"
echo ""

echo "🚀 第5步：测试同步"
echo ""
echo "1. 在 Obsidian 中创建测试文件夹结构"
echo "2. 使用命令 'GitHub Sync: Push to GitHub'"
echo "3. 检查 GitHub 仓库是否正确同步"
echo ""

echo "📝 需要创建的 Obsidian 文件夹结构："
echo ""
echo "您的文库/"
echo "├── 博客文章/"
echo "│   ├── dev/"
echo "│   ├── ai/"
echo "│   └── life/"
echo "├── 博客图片/"
echo "│   ├── images/"
echo "│   └── covers/"
echo "└── 其他笔记/（不会同步）"
echo ""

echo "🎯 完成后效果："
echo "  📝 在 '博客文章/' 下写 .md 文件"
echo "  🖼️ 图片放到 '博客图片/' 对应文件夹"
echo "  🚀 运行同步命令"
echo "  ✅ 自动推送到 GitHub → Vercel 部署"
echo ""

echo "需要我帮您创建这个文件夹结构吗？"