#!/bin/bash

echo "📝 Obsidian 博客发布 - 超简单方案"
echo "================================"
echo ""

echo "🎯 工作流程设计："
echo ""
echo "1. 📖 在 Obsidian 中正常写作"
echo "2. 📁 将完成的文章复制到博客文件夹"
echo "3. 🚀 一键运行发布脚本"
echo "4. ✅ 自动上传图片 + 推送 + 部署"
echo ""

echo "📂 目录结构建议："
echo ""
echo "Obsidian 文库/"
echo "├── 博客草稿/          # 您的正常写作空间"
echo "├── 博客发布/          # 准备发布的文章"
echo "└── 图片资源/          # 文章图片"
echo ""
echo "博客项目/"
echo "├── posts/             # 从 Obsidian 博客发布/ 同步"
echo "├── public/images/     # 从 Obsidian 图片资源/ 同步"
echo "└── 一键发布.sh        # 自动化脚本"
echo ""

echo "🔧 实现方案："
echo ""
echo "方案A: 文件夹软链接（推荐）"
echo "  - 将博客项目的 posts/ 链接到 Obsidian 文库"
echo "  - 在 Obsidian 中直接管理博客文章"
echo "  - 修改即时同步，无需复制"
echo ""
echo "方案B: 自动同步脚本"
echo "  - 脚本自动从 Obsidian 复制文章到博客项目"
echo "  - 自动转换格式和处理图片"
echo "  - 一键完成所有操作"
echo ""
echo "方案C: Obsidian 插件"
echo "  - 使用 Obsidian 发布插件"
echo "  - 直接从 Obsidian 推送到 GitHub"
echo "  - 最简单但需要配置插件"
echo ""

echo "您更喜欢哪种方案？"
echo "A - 文件夹链接（最简单）"
echo "B - 自动同步脚本（功能完整）"  
echo "C - Obsidian 插件（一键发布）"